minecraft-server:
  ports:
    - "25565:25565"
  environment:
    EULA: "TRUE"
  image: itzg/minecraft-server
  container_name: mc-vanilla
  tty: TRUE
  stdin_open: TRUE
  restart: always
  volumes:
    